### PR TITLE
refactor if statement gas

### PR DESCRIPTION
**Pull request by charlesjhongc**

### CODE REVIEW

**Review by pilagod — APPROVED** [review]
It's interesting to see gas diff has no changes in this refactoring 🤣 From my experience the `&&` operator would take the right part into account only if the first expression resolves to `false`. But I'm not sure if this is also true for Solidity 🧐

**Comment by NIC619** [comment]
This refactor should result in gas reduction?

**Comment by NIC619** [comment]
> From my experience the && operator would take the right part into account only if the left expression resolves to `false`.

I think it is "... only if the left expression resolves to `true`"?

**Comment by charlesjhongc** [comment]
Tested in local and yes the gas is reduced a little bit.
Screenshot 2023-07-24 at 3 49 54 PM

**Comment by charlesjhongc** [comment]
@pilagod If you meant there's no gas diff comment, I think it's because the CI setting? Or do you mean there's no gas diff in your local test?

**Review by NIC619 — APPROVED** [review]

**Comment by pilagod** [comment]
I meant gas diff in CI. Yap it seems have some errors generating the report when merging into branches other than `master` 🧐 Thanks for the report screenshot 🙌

**Review by pilagod — APPROVED** [review]

**Pull request merged**
